Repository ucsb-cs156-f23/proj-happycows-f23-5pm-4, pull requests merged in 2023-11, with the labels that each got.

#17 remove toast message and tests
  frontend/src/main/pages/PlayPage.js
  frontend/src/tests/pages/PlayPage.test.js
Labels: FIXME - Need peer CR

#21 Backend for default properties in Commons Create page
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/resources/application.properties
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
Labels: 10

#24 Editing Comments for CommonsForm
  frontend/src/main/components/Commons/CommonsForm.js
Labels: 5

#26 FEATURE: Frontend for default values for Commonds fields in application.properties / env variables
  frontend/src/fixtures/commonsFixtures.js
  frontend/src/main/components/Commons/CommonsForm.js
  frontend/src/tests/components/Commons/CommonsForm.test.js
  src/main/resources/application.properties
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
Labels: 10

#27 Add Last Date field to Commons
  frontend/src/fixtures/commonsFixtures.js
  frontend/src/fixtures/commonsPlusFixtures.js
  frontend/src/main/components/Commons/CommonsForm.js
  frontend/src/main/components/Commons/CommonsTable.js
  frontend/src/main/pages/AdminCreateCommonsPage.js
  frontend/src/main/pages/AdminEditCommonsPage.js
  frontend/src/tests/components/Commons/CommonsCard.test.js
  frontend/src/tests/components/Commons/CommonsForm.test.js
  frontend/src/tests/components/Commons/CommonsTable.test.js
  frontend/src/tests/pages/AdminCreateCommonsPage.test.js
  frontend/src/tests/pages/AdminEditCommonsPage.test.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/Commons.java
  src/main/java/edu/ucsb/cs156/happiercows/models/CreateCommonsParams.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
Labels: 20

#28 Improve chat button UX in play page
  frontend/src/main/components/Chat/ChatContainer.js
  frontend/src/main/components/Chat/ChatToggle.js
  frontend/src/main/pages/PlayPage.js
  frontend/src/stories/components/Chat/ChatContainer.stories.js
  frontend/src/stories/components/Chat/ChatToggle.stories.js
  frontend/src/tests/pages/PlayPage.test.js
Labels: 10

#34 Refactor Start/End dates from LocalDateTime to LocalDate
  frontend/src/fixtures/commonsFixtures.js
  frontend/src/fixtures/commonsPlusFixtures.js
  frontend/src/fixtures/reportFixtures.js
  frontend/src/fixtures/reportLineFixtures.js
  frontend/src/main/components/Commons/CommonsForm.js
  frontend/src/main/components/Commons/CommonsTable.js
  frontend/src/tests/components/Commons/CommonsForm.test.js
  frontend/src/tests/pages/AdminCreateCommonsPage.test.js
  src/main/java/edu/ucsb/cs156/happiercows/entities/Commons.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/Report.java
  src/main/java/edu/ucsb/cs156/happiercows/models/CreateCommonsParams.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonStatsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/ReportsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/MilkTheCowsJobIndTests.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/MilkTheCowsJobTests.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/SetCowHealthJobTests.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/UpdateCowHealthJobIndTests.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/UpdateCowHealthJobTests.java
  src/test/java/edu/ucsb/cs156/happiercows/services/AverageCowHealthServiceTests.java
  src/test/java/edu/ucsb/cs156/happiercows/services/CommonStatsServiceTests.java
  src/test/java/edu/ucsb/cs156/happiercows/services/CommonsPlusBuilderServiceTests.java
  src/test/java/edu/ucsb/cs156/happiercows/services/ReportServiceTests.java
Labels: 10, Merge Candidate
