Repository ucsb-cs156-f23/proj-happycows-f23-5pm-4, pull requests merged in 2023-12, with the labels that each got.

#36 Issue B1: Backend, Add Entity / Repository for announcements
  frontend/src/main/components/Commons/CommonsPlay.css
  src/main/java/edu/ucsb/cs156/happiercows/entities/AnnouncementsTable.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/AnnouncementsTableRepository.java
Labels: 5, Merge Candidate

#37 add gameInProgress()
  src/main/java/edu/ucsb/cs156/happiercows/entities/Commons.java
  src/main/java/edu/ucsb/cs156/happiercows/jobs/MilkTheCowsJob.java
  src/main/java/edu/ucsb/cs156/happiercows/jobs/UpdateCowHealthJob.java
  src/test/java/edu/ucsb/cs156/happiercows/entities/CommonsTests.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/MilkTheCowsJobTests.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/UpdateCowHealthJobTests.java
Labels: 10, Merge Candidate

#33 Further UI/UX improvements for commons chat
  frontend/src/main/components/Chat/ChatDisplay.js
  frontend/src/main/components/Chat/ChatMessageDisplay.js
  frontend/src/tests/components/Chat/ChatDisplay.test.js
  frontend/src/tests/components/Chat/ChatMessageDisplay.test.js
Labels: 5
